// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIzf7wk0s3mQ-R52NK8aw8efyI-9sBFb4',
    appId: '1:239702932292:web:2c3109a04bf254e181b511',
    messagingSenderId: '239702932292',
    projectId: 'hrms-attendance-app',
    authDomain: 'hrms-attendance-app.firebaseapp.com',
    storageBucket: 'hrms-attendance-app.appspot.com',
    measurementId: 'G-Q4PDN4Z65D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCXslZmyhEKowPp1gwCCttuX5Jn5NJ0v4',
    appId: '1:239702932292:android:460e6fb015c5861181b511',
    messagingSenderId: '239702932292',
    projectId: 'hrms-attendance-app',
    storageBucket: 'hrms-attendance-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSz-jPTYs_-2QpFlY9ZS6_OZQWO_-k18c',
    appId: '1:239702932292:ios:f771ec44d214554b81b511',
    messagingSenderId: '239702932292',
    projectId: 'hrms-attendance-app',
    storageBucket: 'hrms-attendance-app.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSz-jPTYs_-2QpFlY9ZS6_OZQWO_-k18c',
    appId: '1:239702932292:ios:f771ec44d214554b81b511',
    messagingSenderId: '239702932292',
    projectId: 'hrms-attendance-app',
    storageBucket: 'hrms-attendance-app.appspot.com',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIzf7wk0s3mQ-R52NK8aw8efyI-9sBFb4',
    appId: '1:239702932292:web:6190ddae65f85c3481b511',
    messagingSenderId: '239702932292',
    projectId: 'hrms-attendance-app',
    authDomain: 'hrms-attendance-app.firebaseapp.com',
    storageBucket: 'hrms-attendance-app.appspot.com',
    measurementId: 'G-L4Z7WVXFVV',
  );
}
